var Template = module.exports = require('./main')
  , for_handler = require('./for')
  , if_handler = require('./if')
  , value = require('./value')
  , html = require('./html')
  , attr = require('./attr')

Template.add_tag('altr-attr', attr)
Template.add_tag('altr-html', html)
Template.add_tag('altr-value', value)
Template.add_tag('altr-if', if_handler)
Template.add_tag('altr-for', for_handler)
