var placeholder = require('./tags/placeholder')
var childrenTag = require('./tags/children')
var includeTag = require('./tags/include')
var textTag = require('./tags/text')
var htmlTag = require('./tags/html')
var withTag = require('./tags/with')
var forTag = require('./tags/for')
var rawTag = require('./tags/raw')
var ifTag = require('./tags/if')
var altr = require('./altr')

module.exports = altr

altr.addTag('altr-children', childrenTag)
altr.addTag('altr-replace', placeholder)
altr.addTag('altr-include', includeTag)
altr.addTag('altr-text', textTag)
altr.addTag('altr-html', htmlTag)
altr.addTag('altr-with', withTag)
altr.addTag('altr-for', forTag)
altr.addTag('altr-raw', rawTag)
altr.addTag('altr-if', ifTag)
